### PR TITLE
Fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Check if `stdatomic.h` is available before using it to fix the following build failure raised since version 1.46 and https://github.com/hreinecke/sg3_utils/commit/e9445f4efc012d37809342ba21f16360a0208f06:

```
sgp_dd.c:67:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
```

Fixes:
 - http://autobuild.buildroot.org/results/2f531a187dd8e4c709bc0d81f8d4cb36ef5f5437

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by doug-gilbert** [comment]
Thanks for the patch, independently I added the same thing a few days back. And you made the same mistake that I did in my first patch. The extra check proposed in sgp_dd.c is _before_ config.h is included so HAVE_STDATOMIC_H will never be defined. Great minds think alike!
The fix should appear in a few hours in a new revision here.

**Comment by ffontaine** [comment]
Good, I'm closing this PR then.

**Comment by doug-gilbert** [comment]
Fix is in revision 918 which is now present here in github.
